### ISSUE TITLE
Is this code working for you?

### ISSUE THREAD

**Issue by r-chris** [tizpuppi/ngx_http_auth_jwt_module#1]
Sorry if this sounds impolite - I couldn't find a better title for this, though. I am absolutely assuming that I am not reading your code correctly here, but before I go in further, I was hoping you @tizpuppi could please let me know if you have been / are running this code somewhere successfully or if I should interpret this as a work-in-progress?

**What did I do so far?**
- Compiled Nginx with this as an additional module
- Setup config as described and confirmed that access to specific route is blocked with `401 unauthorized` via this NGINX module
- Turned on the NGINX debug error log level to see as much relevant info I could get
- Trying to now actually get myself authentication (via `token=$cookie_...`), but am still consistently receiving `401 unauthorized` from NGINX
- Started to read through the code and tried to understand at which point the user is actually being authorized
- Started wondering if there may be are bugs maybe here:

https://github.com/tizpuppi/ngx_http_auth_jwt_module/blob/bf8ae5fd4b8e981b7683990378356181dee93842/ngx_http_auth_jwt_module.c#L247

and / or here:

https://github.com/tizpuppi/ngx_http_auth_jwt_module/blob/bf8ae5fd4b8e981b7683990378356181dee93842/ngx_http_auth_jwt_module.c#L271

**Comment by r-chris** [comment]
From my NGINX error log (debug mode) I can tell that the code is reaching this line:
https://github.com/tizpuppi/ngx_http_auth_jwt_module/blob/bf8ae5fd4b8e981b7683990378356181dee93842/ngx_http_auth_jwt_module.c#L249

However, the `strerror(errno)` value is actually `SUCCESS`, which I assume means the `jwt_decode` call above was actually successful? Was there maybe a different assumption about what `err` should be or is it actually correct to enter this `if` statement here?

The code in that specific `if (err)` statement then goes on to call `ngx_http_auth_jwt_set_realm`:
https://github.com/tizpuppi/ngx_http_auth_jwt_module/blob/bf8ae5fd4b8e981b7683990378356181dee93842/ngx_http_auth_jwt_module.c#L250

which will eventually return `NGX_HTTP_UNAUTHORIZED`:
https://github.com/tizpuppi/ngx_http_auth_jwt_module/blob/bf8ae5fd4b8e981b7683990378356181dee93842/ngx_http_auth_jwt_module.c#L303

(or `NGX_HTTP_INTERNAL_SERVER_ERROR` as the only other return path)

Even if we wouldn't have entered that `if` statement above, the function `ngx_http_auth_jwt_handler ` would have returned `NGX_DECLINED`:
https://github.com/tizpuppi/ngx_http_auth_jwt_module/blob/bf8ae5fd4b8e981b7683990378356181dee93842/ngx_http_auth_jwt_module.c#L271

So, I guess my question is **where** in the code does NGINX actually allows the request to pass through, because I couldn't immediately spot it, but then again I'm not exactly familiar with how the NGINX module architecture works.

Either way, thanks for providing this repo and I hope you get around the comment on my questions.

**Comment by tizpuppi** [comment]
Dear Chris,

a small explanation before going to your question.
As stated in the NGINX documentation, NGX_DECLINED is a return code that means: "Operation rejected, for example, because it is disabled in the configuration. This is never an error." To say this in simple terms, this means that the module has finished to handle the request and "passes" control to the next module in the pipeline. (At the beginning I was also confused by this name!)

So if you reach the line https://github.com/tizpuppi/ngx_http_auth_jwt_module/blob/bf8ae5fd4b8e981b7683990378356181dee93842/ngx_http_auth_jwt_module.c#L249 it means that the jwt verification failed. As a side not, I am more surprised that strerror(errno) value is actually SUCCESS.

So in order to better understand why you are not able to use it, can you please paste here the jwt you are using and the public key (in case the JWT has been signed with a private/public key pair) or the secret key (in case the jwt has been created using a symmetric key)?

Thank you

**Comment by r-chris** [comment]
Ok, thanks for the immediate reply. That's definitely relevant to know and not intuitive, since I've been looking at similar implementation, which appear to be returning `NGINX_OK` in that almost identical scenario and in their implementation they appear to use `NGX_DECLINED` as a return only if the whole module is not supposed to be active:

https://github.com/maxx-t/nginx-jwt-module/blob/d9a2ece81ca66647f81fc2586b29b348af67f8aa/src/ngx_http_auth_jwt_module.c#L143

**Comment by r-chris** [comment]
I can probably setup a dummy-app and share that with you, but I won't get that going until tomorrow. I have been using `auth0` for these tests and this is what the relevant part of my test Nginx config looks like (in case it helps):

    location = /application {
        auth_jwt "application" token=$cookie_lt_jwt;
        auth_jwt_key_file /usr/src/lt/nginx/lt.sec;
        auth_jwt_alg HS256;

        root /usr/src/lt/nginx;
        try_files /application.html =404;
    }

Initially, it was configured with `RS256`, but since I was running into trouble I thought `HS256` might work better. I'm actually not really sure what the `realm` in `auth_jwt "application"` should be set to and initially read an article by auth0 that put their url there as a string (https://auth0.com/blog/use-nginx-plus-and-auth0-to-authenticate-api-clients/) `auth_jwt "YOUR-AUTH0-DOMAIN.auth0.com";` Do you possibly have any suggestions what I need to put there?

Thanks!
